$schema: 'http://json-schema.org/schema#'
required:
  - user
type: object
properties:
  user:
    required:
      - activated
      - avatar
      - connectedAccounts
      - connectedSlack
      - created
      - email
      - isRestricted
      - isVerified
      - lastLoginMobile
      - lastSeen
      - level
      - name
      - notifications
      - oldPassword
      - password
      - skipConfirmationEmail
      - spaces
      - timezone
    type: object
    properties:
      skipConfirmationEmail:
        type: boolean
      oldPassword:
        type: 'null'
      name:
        type: string
      created:
        type: 'null'
      level:
        type: integer
      activated:
        type: boolean
      connectedAccounts:
        type: object
      notifications:
        type: array
      connectedSlack:
        type: boolean
      spaces:
        type: array
      lastSeen:
        type: 'null'
      isRestricted:
        type: boolean
      timezone:
        type: 'null'
      lastLoginMobile:
        type: 'null'
      password:
        type: 'null'
      email:
        type: string
      isVerified:
        type: boolean
      avatar:
        type: 'null'